### PR TITLE
draft tweet about hackathon

### PR DESCRIPTION
**Pull request by bast**
@rkdarst

### CODE REVIEW

**Review by rkdarst — APPROVED** [review]
Looks good to me, but I wonder if linking straight to the hackmd is the best idea (for various reasons like getting random edits, does it direct people to us, or the fact that there are names directly on it).  An alternate suggestion is to link to https://coderefinery.github.io/manuals/chat/ (or maybe coderefinery.zulipchat.com), and hope people introduce themselves and we direct them to the spot?

Do we have a better landing page?

**Comment by bast** [comment]
Good suggestion. I was thinking about that. Let me adjust the text in a moment.

**Review by naoe-tatara — APPROVED** [review]
I cannot remember how Zulip looks like when you first join, but it would be nice to put something like a sign post in the Zulip where the new participants can go to join in the Hackathon? Sorry for throwing things to you guys, but good luck!

**Comment by bast** [comment]
I agree that a signpost would be nice. Let's see if I find time to experiment with that.

**Pull request merged**
