### PR TITLE
tweets/2021/10/python-1: Python for scicomp tweet 1

### PR DESCRIPTION
**Pull request by rkdarst**

### CODE REVIEW

**Comment by naoe-tatara** [comment]
Personally, I would rather delete ": people from Finland, Sweden, Norway can register for exercise sessions" and instead say "no registration required", then it sounds more inclusive rather than limiting countries for registration for not even guaranteed seats (if it might be misleading)? But of course, maybe not many expects "registration for exercise session" = "getting seats to be in a BO room with access to helper via video"??

**Comment by rkdarst** [comment]
Updated with your suggestion.  This is a good idea, we can do
follow-ups with this as "why it is cool" about registrations and so on

**Comment by naoe-tatara** [comment]
? I see only one original commit and no file changes, but do I look at different place??

**Review by naoe-tatara — APPROVED** [review]
:)

**Pull request merged**
