### PR TITLE
after onboarding tweet

### PR DESCRIPTION
**Pull request by samumantha**
no idea about the #, feel free to add/change :)

### CODE REVIEW

**Comment by bast** [comment]
It seems it's too long. Can I help somehow?

**Review by bast — APPROVED** [review]

**Comment by bast** [comment]
Maybe somebody else can double-check my changes and merge or adjust?

**Review by annefou — APPROVED** [review]
This is great! Thanks.

**Comment by naoe-tatara** [comment]
Looks great, thanks! I didn't know about this repo, sorry!

**Review by naoe-tatara — APPROVED** [review]

**Pull request merged**
