### PR TITLE
tweet about new install instructions

### PR DESCRIPTION
**Pull request by bast**
of course please add/remove/edit

### CODE REVIEW

**Review by naoe-tatara — APPROVED** [review]
Looks great :) Thanks!

**Review by johanhellsvik — COMMENTED** [review]
Reads well. Change to end the second sentence with an exclamation mark?

**Comment by bast** [comment]
> Reads well. Change to end the second sentence with an exclamation mark?

Thanks! Please edit here and add the exclamation mark via the comment -> +/- symbol. Not trying to avoid work on my side, just want to show that you can edit it here. Unless you are pressed on time.

**Comment by johanhellsvik** [comment]
Thanks! I have done the change.

**Review by johanhellsvik — APPROVED** [review]

**Comment by bast** [comment]
Thanks! Did you do it via command line or via web UI? I meant web UI since that would be quicker, I didn't mean to create more command line work for you.

**Comment by johanhellsvik** [comment]
Via the web UI. It was the first time for me to use that functionality - now I know how it goes!

**Pull request merged**
