### PR TITLE
Announce videos for May 2021 CR workshop

### PR DESCRIPTION
**Pull request by PatricHolmvall**
Tweet that the videos have been uploaded for the for the May 2021 CR Workshop.

As always, feel free to edit and completely rewrite.

### CODE REVIEW

**Review by naoe-tatara — APPROVED** [review]
I think this is good :) Thanks @PatricHolmvall !

**Review by bast — APPROVED** [review]
Thanks so much!

**Comment by bast** [comment]
I just realized that Patric perhaps cannot merge. If you like I can add you to the GitHub organization so that you can also merge these?

**Comment by PatricHolmvall** [comment]
> I just realized that Patric perhaps cannot merge. If you like I can add you to the GitHub organization so that you can also merge these?

If you feel that this is appropriate, then sure.

**Comment by bast** [comment]
Invite sent.

**Pull request merged**
